### ISSUE TITLE
How to transform this pkf as ROS1 version?

### ISSUE THREAD

**Issue by crankler** [adyczech/global_elevation_mapping#1]
Hi, thanks for your work, can you tell me how to transform this pkg so that I can used in ROS1 environment?

**Comment by adyczech** [comment]
Hi,
you would have to port all files (CMake, src, package.xml, launch, ...) to ROS1. This package is fairly simple so the process should not take too long. I'm considering porting the package myself, but I can't give you a firm timeline at this point.

**Comment by crankler** [comment]
Yes, thank you for your points.
I will try to rewirte your suggestion.
